In [125]:
import numpy as np
import pandas as pd
import random

In [126]:
Lista = [[1, 2, 3], [4, 5, 6]]
print(Lista)

[[1, 2, 3], [4, 5, 6]]


In [127]:
array1 = np.array(Lista)
print(array1.dtype)
array1 = np.array(Lista, dtype=np.int8)
print(array1.dtype)
print(array1)

int32
int8
[[1 2 3]
 [4 5 6]]


In [128]:
array1?

Type:            ndarray
String form:    
[[1 2 3]
 [4 5 6]]
Length:          2
File:            c:\programdata\anaconda3\lib\site-packages\numpy\__init__.py
Docstring:       <no docstring>
Class docstring:
ndarray(shape, dtype=float, buffer=None, offset=0,
        strides=None, order=None)

An array object represents a multidimensional, homogeneous array
of fixed-size items.  An associated data-type object describes the
format of each element in the array (its byte-order, how many bytes it
occupies in memory, whether it is an integer, a floating point number,
or something else, etc.)

Arrays should be constructed using `array`, `zeros` or `empty` (refer
to the See Also section below).  The parameters given here refer to
a low-level method (`ndarray(...)`) for instantiating an array.

For more information, refer to the `numpy` module and examine the
methods and attributes of an array.

Parameters
----------
(for the __new__ method; see Notes below)

shape : tuple of ints
    Shape of c

In [129]:
Array2 = np.arange(10, 100, 5, dtype=np.int8)
print(Array2)
print(Array2.dtype)

[10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]
int8


In [130]:
Array3 = np.linspace(1.0, 2.0, num=50)
print(Array3)

[1.         1.02040816 1.04081633 1.06122449 1.08163265 1.10204082
 1.12244898 1.14285714 1.16326531 1.18367347 1.20408163 1.2244898
 1.24489796 1.26530612 1.28571429 1.30612245 1.32653061 1.34693878
 1.36734694 1.3877551  1.40816327 1.42857143 1.44897959 1.46938776
 1.48979592 1.51020408 1.53061224 1.55102041 1.57142857 1.59183673
 1.6122449  1.63265306 1.65306122 1.67346939 1.69387755 1.71428571
 1.73469388 1.75510204 1.7755102  1.79591837 1.81632653 1.83673469
 1.85714286 1.87755102 1.89795918 1.91836735 1.93877551 1.95918367
 1.97959184 2.        ]


In [131]:
Array4 = np.zeros((5, 4))
print(Array4)
Array4 = np.ones((4, 5))
print(Array4)
Array4 = np.identity(4)
print(Array4)
Array4 = np.eye(4, 6, 2) #En que columna empiesa la digonal de 1.
print(Array4)
Array4 = np.full((2, 5), 10)
print(Array4)
Array4 = np.random.random((2, 5))
print(Array4)
Array4 = np.random.randint(0, 100, size=(5, 6))
print(Array4)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]
[[10 10 10 10 10]
 [10 10 10 10 10]]
[[0.68917705 0.45558585 0.66567742 0.22617236 0.05723673]
 [0.68822178 0.20560561 0.08881759 0.18046268 0.38709525]]
[[54 73 69 72 99 82]
 [16 10 23  0 36  4]
 [89 45 46 23 62 48]
 [94 37 67 31 81 30]
 [55 23 69 34 39 54]]


In [132]:
archivo = np.loadtxt("C:\\Users\\matia\\Desktop\\EducacionIT\\Archivos\\Matriz.txt", delimiter=",", dtype=np.int8)
print(archivo)

[[1 2 3]
 [2 3 4]
 [3 4 5]]


In [133]:
print(archivo.dtype)
print(archivo.size)
print(archivo.nbytes)
print(archivo.ndim)
print(archivo.shape)
print(archivo.strides)#Cuantos bytes se necesitan para saltar de una fila a otra.

int8
9
9
2
(3, 3)
(3, 1)


In [134]:
fecha = np.array(["2007-07-13", "2006-01-13", "2010-12-13"], dtype="datetime64")
print(fecha)
print(fecha + 30)

['2007-07-13' '2006-01-13' '2010-12-13']
['2007-08-12' '2006-02-12' '2011-01-12']


In [135]:
print(Array4)
print(Array4.shape, "5*6 = 30 elementos.")

Array5 = Array4.reshape(3, 10)
print(Array5, "\n", Array5.shape, "3*10 = 30 elementos.")

[[54 73 69 72 99 82]
 [16 10 23  0 36  4]
 [89 45 46 23 62 48]
 [94 37 67 31 81 30]
 [55 23 69 34 39 54]]
(5, 6) 5*6 = 30 elementos.
[[54 73 69 72 99 82 16 10 23  0]
 [36  4 89 45 46 23 62 48 94 37]
 [67 31 81 30 55 23 69 34 39 54]] 
 (3, 10) 3*10 = 30 elementos.


In [136]:
print(Array4)
print(Array4[2, 4], Array4[2][4])
print(Array4[2, :])
print(Array4[1:3, 1:4])#El ultimo del rango no se cuenta, es abierto.
print(Array4[-1, -1])

[[54 73 69 72 99 82]
 [16 10 23  0 36  4]
 [89 45 46 23 62 48]
 [94 37 67 31 81 30]
 [55 23 69 34 39 54]]
62 62
[89 45 46 23 62 48]
[[10 23  0]
 [45 46 23]]
54


In [137]:
Array6 = np.random.randint(0, 10, 10)
print(Array6)
ArrayBooleans = np.array([True, False, True, False, True, False, True, False, True, False])
print(ArrayBooleans)
print(Array6.size, " = ", ArrayBooleans.size)
Array6[ArrayBooleans] #Solo devuelve los True. 

[6 5 4 7 4 7 1 9 0 5]
[ True False  True False  True False  True False  True False]
10  =  10


array([6, 4, 4, 1, 0])

In [142]:
print(Array4)
print(Array4 < 50)
print(Array4[Array4<50])
print(Array4[(Array4>30) & (Array4<70)])
Array4[(Array4%3==0)] = 10000
print(Array4)

[[99 73 99 99 99 82]
 [16 10 23 99 99  4]
 [89 99 46 23 62 99]
 [94 37 67 31 99 99]
 [55 23 99 34 99 99]]
[[False False False False False False]
 [ True  True  True False False  True]
 [False False  True  True False False]
 [False  True False  True False False]
 [False  True False  True False False]]
[16 10 23  4 46 23 37 31 23 34]
[46 62 37 67 31 55 34]
[[10000    73 10000 10000 10000    82]
 [   16    10    23 10000 10000     4]
 [   89 10000    46    23    62 10000]
 [   94    37    67    31 10000 10000]
 [   55    23 10000    34 10000 10000]]


In [151]:
Array4[Array4==10000] = random.randint(1, 100)
Array7 = np.random.randint(1, 100, size=(6, 5))
print("Array4:\n", Array4, "\nArray7:\n", Array7)

Array4:
 [[91 73 91 91 91 82]
 [16 10 23 91 91  4]
 [89 91 46 23 62 91]
 [94 37 67 31 91 91]
 [55 23 91 34 91 91]] 
Array7:
 [[14 27 41 84 55]
 [ 1 31 53 51 78]
 [52  7 76 51 80]
 [82 28 12 94 83]
 [77 94 64 29 30]
 [75 25 93 38 54]]
