In [2]:
import numpy as np
import pandas as pd
import random

- Ejercicio 1

    - A- Construir arrays a partir de una lista simple y una lista anidada usando tipos de datos numéricos distintos para cada una.
    -B- Construir un array lineal de 36 elementos. Cambiar el shape para que tenga:
        - 3 filas y 12 columnas 
        - 4 columnas 

    
Parte A:

In [13]:
ListaSimple = [1, 2, 3, 4]
MatrizSimple = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

Array1 = np.array(ListaSimple)
Matriz1 = np.array(MatrizSimple)
print(Array1, "\n", Matriz1)

[1 2 3 4] 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


PARTE B:

In [25]:
Array2 = np.random.randint(0, 100, 36)
print("Array2: ", Array2)

Array3 = Array2.reshape(3, 12)
print(Array3)
Array3 = Array2.reshape(9, 4)
print(Array3)


Array2:  [85 59 86 52 48  8 33 71 13 20  4 45 60  8 91  4  8 64 93 58 47 71 78 84
 48 72 11 98  7  6 45 23 85 17 46  1]
[[85 59 86 52 48  8 33 71 13 20  4 45]
 [60  8 91  4  8 64 93 58 47 71 78 84]
 [48 72 11 98  7  6 45 23 85 17 46  1]]
[[85 59 86 52]
 [48  8 33 71]
 [13 20  4 45]
 [60  8 91  4]
 [ 8 64 93 58]
 [47 71 78 84]
 [48 72 11 98]
 [ 7  6 45 23]
 [85 17 46  1]]


- Ejercicio 2 
    - Dado un vector de pesos(kg) y otro vector alturas(metros), calcular el índice de masa corporal general (un vector imc).


In [29]:
Pesos = np.array([78, 75.5, 80, 81.3])
Alturas = np.array([1.74, 1.78, 1.71, 1.85])

imc = Pesos/(Alturas**2)
imc

array([25.76298058, 23.82906199, 27.35884546, 23.75456538])

- Ejercicio 3
    - Crear un vector con diez números, todos ceros
    - Crear un vector con diez números al azar
    - Crear una matriz de 2x3 y multiplicarla por su transpuesta

In [51]:
Ceros = np.zeros(10)
print(Ceros)

Azar = np.random.randint(0, 10, 10)
print(Azar)

Matriz = np.array([[2, 3, 4], [3, 4, 5]])
print(Matriz)
MatrizTranspuesta = Matriz.transpose()
print(MatrizTranspuesta)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1 9 3 6 7 1 3 7 6 3]
[[2 3 4]
 [3 4 5]]
[[2 3]
 [3 4]
 [4 5]]
