In [11]:
import numpy as np
import pandas as pd
import matplotlib as plt
import random

Funciones de agregacion

In [12]:
Ventas = np.random.randint(1, 10, size=20).reshape(4, 5)#Cada fila es 1 semana, y cada columna es un dia de la semana
print(Ventas)

[[7 5 7 6 5]
 [2 9 4 4 3]
 [4 5 3 1 4]
 [5 4 7 7 2]]


In [13]:
print(Ventas)
print(Ventas.max())
print(Ventas.min())
print(Ventas.prod())#Multiplica todos los elementos del array.
print(Ventas.cumsum(axis=1))#Va sumando y poniendo los elementos de las filas (axis=0 son para las columnas).

[[7 5 7 6 5]
 [2 9 4 4 3]
 [4 5 3 1 4]
 [5 4 7 7 2]]
9
1
-2069078016
[[ 7 12 19 25 30]
 [ 2 11 15 19 22]
 [ 4  9 12 13 17]
 [ 5  9 16 23 25]]


In [14]:
print(Ventas.argmax(), Ventas.argmin())

6 13


###Producto escalar

In [15]:
V = np.array([1, 2, 3, 4])
W = np.array([5, 6, 7, 8])
print("V@W = ", V@W, ", [1, 2, 3, 4].[5, 6, 7, 8] = 1.5+2.6+7.7+4.8 = ", V@W)
print(V@W, " = ", V.dot(W))

V@W =  70 , [1, 2, 3, 4].[5, 6, 7, 8] = 1.5+2.6+7.7+4.8 =  70
70  =  70


In [23]:
A = np.array([[2, 5, 3], [7, 1, 4]])
B = np.array([[3, 2], [9, 6], [5, 8]])
print( "A.B = \n", A.dot(B))

A.B = 
 [[66 58]
 [50 52]]


In [80]:
a = np.arange(49).reshape(7, 7)
print(a)
print(a.T, " = \n", a.transpose())


[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]
 [35 36 37 38 39 40 41]
 [42 43 44 45 46 47 48]]
[[ 0  7 14 21 28 35 42]
 [ 1  8 15 22 29 36 43]
 [ 2  9 16 23 30 37 44]
 [ 3 10 17 24 31 38 45]
 [ 4 11 18 25 32 39 46]
 [ 5 12 19 26 33 40 47]
 [ 6 13 20 27 34 41 48]]  = 
 [[ 0  7 14 21 28 35 42]
 [ 1  8 15 22 29 36 43]
 [ 2  9 16 23 30 37 44]
 [ 3 10 17 24 31 38 45]
 [ 4 11 18 25 32 39 46]
 [ 5 12 19 26 33 40 47]
 [ 6 13 20 27 34 41 48]]


### Pandas

In [91]:
Ser = pd.Series([1, 2, 3, 4, 5])
print(Ser)

Ser = pd.Series([1, 2, 3, 4, 5], index=["a", "b", "c", "d", "e"], dtype="int8", name="Numeros")
print(Ser)

Ser1 = pd.Series({"Jose":10000, "Maria":12500, "Mariano":80000, "Analia":20000}, name = "Saldo")
print(Ser1)

0    1
1    2
2    3
3    4
4    5
dtype: int64
a    1
b    2
c    3
d    4
e    5
Name: Numeros, dtype: int8
Jose       10000
Maria      12500
Mariano    80000
Analia     20000
Name: Saldo, dtype: int64


In [96]:
Data = np.array(["Enero", "Febrero", "Marzo", "Abril", "Mayo"])
Ser2 = pd.Series(Data, index=[1, 2, 3, 4, 5])
print(Ser2)

1      Enero
2    Febrero
3      Marzo
4      Abril
5       Mayo
dtype: object


In [98]:
df = pd.DataFrame([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
df1 = pd.DataFrame([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14], [15, 16, 17, 18, 19]], index=["Semana1", "Semana2", "Semana3", "Semana4"], columns=["Lunes", "Martes", "Miercoles", "Jueves", "Viernes"])

print(df)
print(df1)

   0  1  2
0  0  1  2
1  3  4  5
2  6  7  8
         Lunes  Martes  Miercoles  Jueves  Viernes
Semana1      0       1          2       3        4
Semana2      5       6          7       8        9
Semana3     10      11         12      13       14
Semana4     15      16         17      18       19


In [99]:
array = np.random.randint(0, 50, (4, 3))
pd.DataFrame(array, index=["CABA", "Buenos Aires", "Cordoba", "Santa fe"], columns=["Enero", "Febrero", "Marzo"])

Enero  Febrero  Marzo
CABA             27       10      3
Buenos Aires     18       29     34
Cordoba          17       15     41
Santa fe         12       11     32

In [100]:
pd.DataFrame({"Columna 1":[100, 125, 75], "Columna 2":[100, 125, 75], "Columna 3":[100, 125, 75], "Columna 4":[100, 125, 75]}, index=["A", "B", "C"])

Columna 1  Columna 2  Columna 3  Columna 4
A        100        100        100        100
B        125        125        125        125
C         75         75         75         75

In [106]:
data = pd.read_csv("C:\\Users\\matia\\Desktop\\EducacionIT\\Archivos\\titanic.csv")
print(data)

     PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ... 

In [110]:
data.head()
data.tail(10)

PassengerId  Survived  Pclass                                      Name  \
881          882         0       3                        Markun, Mr. Johann   
882          883         0       3              Dahlberg, Miss. Gerda Ulrika   
883          884         0       2             Banfield, Mr. Frederick James   
884          885         0       3                    Sutehall, Mr. Henry Jr   
885          886         0       3      Rice, Mrs. William (Margaret Norton)   
886          887         0       2                     Montvila, Rev. Juozas   
887          888         1       1              Graham, Miss. Margaret Edith   
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"   
889          890         1       1                     Behr, Mr. Karl Howell   
890          891         0       3                       Dooley, Mr. Patrick   

        Sex   Age  SibSp  Parch            Ticket     Fare Cabin Embarked  
881    male  33.0      0      0            349257   7.8958   NaN        S  
882  female  22.0      0      0              7552  10.5167   NaN        S  
883    male  28.0      0      0  C.A./SOTON 34068  10.5000   NaN        S  
884    male  25.0      0      0   SOTON/OQ 392076   7.0500   NaN        S  
885  female  39.0      0      5            382652  29.1250   NaN        Q  
886    male  27.0      0      0            211536  13.0000   NaN        S  
887  female  19.0      0      0            112053  30.0000   B42        S  
888  female   NaN      1      2        W./C. 6607  23.4500   NaN        S  
889    male  26.0      0      0            111369  30.0000  C148        C  
890    male  32.0      0      0            370376   7.7500   NaN        Q

In [111]:
data.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [113]:
data[["Name", "Age", "Sex"]]

Name   Age     Sex
0                              Braund, Mr. Owen Harris  22.0    male
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0  female
2                               Heikkinen, Miss. Laina  26.0  female
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0  female
4                             Allen, Mr. William Henry  35.0    male
..                                                 ...   ...     ...
886                              Montvila, Rev. Juozas  27.0    male
887                       Graham, Miss. Margaret Edith  19.0  female
888           Johnston, Miss. Catherine Helen "Carrie"   NaN  female
889                              Behr, Mr. Karl Howell  26.0    male
890                                Dooley, Mr. Patrick  32.0    male

[891 rows x 3 columns]

In [116]:
data.loc[38, ["Name", "Age", "Sex"]]

Name    Vander Planke, Miss. Augusta Maria
Age                                   18.0
Sex                                 female
Name: 38, dtype: object

In [123]:
data.loc[25:39, ["Name", "Age", "Sex"]]

Name   Age     Sex
25  Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...  38.0  female
26                            Emir, Mr. Farred Chehab   NaN    male
27                     Fortune, Mr. Charles Alexander  19.0    male
28                      O'Dwyer, Miss. Ellen "Nellie"   NaN  female
29                                Todoroff, Mr. Lalio   NaN    male
30                           Uruchurtu, Don. Manuel E  40.0    male
31     Spencer, Mrs. William Augustus (Marie Eugenie)   NaN  female
32                           Glynn, Miss. Mary Agatha   NaN  female
33                              Wheadon, Mr. Edward H  66.0    male
34                            Meyer, Mr. Edgar Joseph  28.0    male
35                     Holverson, Mr. Alexander Oskar  42.0    male
36                                   Mamee, Mr. Hanna   NaN    male
37                           Cann, Mr. Ernest Charles  21.0    male
38                 Vander Planke, Miss. Augusta Maria  18.0  female
39                        Nicola-Yarred, Miss. Jamila  14.0  female

In [124]:
data.loc[[20, 25], ["Name", "Age", "Sex"]]

Name   Age     Sex
20                               Fynney, Mr. Joseph J  35.0    male
25  Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...  38.0  female

In [125]:
data.iloc[150:170, -4:]

Ticket     Fare Cabin Embarked
150      S.O.P. 1166  12.5250   NaN        S
151           113776  66.6000    C2        S
152       A.5. 11206   8.0500   NaN        S
153         A/5. 851  14.5000   NaN        S
154        Fa 265302   7.3125   NaN        S
155         PC 17597  61.3792   NaN        C
156            35851   7.7333   NaN        Q
157  SOTON/OQ 392090   8.0500   NaN        S
158           315037   8.6625   NaN        S
159         CA. 2343  69.5500   NaN        S
160           371362  16.1000   NaN        S
161       C.A. 33595  15.7500   NaN        S
162           347068   7.7750   NaN        S
163           315093   8.6625   NaN        S
164          3101295  39.6875   NaN        S
165           363291  20.5250   NaN        S
166           113505  55.0000   E33        S
167           347088  27.9000   NaN        S
168         PC 17318  25.9250   NaN        S
169             1601  56.4958   NaN        S

In [126]:
data.iloc[[120, 125], [1, 2, 3, 4]]

Survived  Pclass                          Name   Sex
120         0       2   Hickman, Mr. Stanley George  male
125         1       3  Nicola-Yarred, Master. Elias  male

In [127]:
data.iloc[124, 4]

'male'

In [130]:
data["Age"]>=30
data[data["Age"]>=30]

PassengerId  Survived  Pclass  \
1              2         1       1   
3              4         1       1   
4              5         0       3   
6              7         0       1   
11            12         1       1   
..           ...       ...     ...   
873          874         0       3   
879          880         1       1   
881          882         0       3   
885          886         0       3   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
6                              McCarthy, Mr. Timothy J    male  54.0      0   
11                            Bonnell, Miss. Elizabeth  female  58.0      0   
..                                                 ...     ...   ...    ...   
873                        Vander Cruyssen, Mr. Victor    male  47.0      0   
879      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)  female  56.0      0   
881                                 Markun, Mr. Johann    male  33.0      0   
885               Rice, Mrs. William (Margaret Norton)  female  39.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch    Ticket     Fare Cabin Embarked  
1        0  PC 17599  71.2833   C85        C  
3        0    113803  53.1000  C123        S  
4        0    373450   8.0500   NaN        S  
6        0     17463  51.8625   E46        S  
11       0    113783  26.5500  C103        S  
..     ...       ...      ...   ...      ...  
873      0    345765   9.0000   NaN        S  
879      1     11767  83.1583   C50        C  
881      0    349257   7.8958   NaN        S  
885      5    382652  29.1250   NaN        Q  
890      0    370376   7.7500   NaN        Q  

[330 rows x 12 columns]

In [133]:
data[(data["Age"]>=30) & (data["Sex"]=="male")]

PassengerId  Survived  Pclass                                  Name  \
4              5         0       3              Allen, Mr. William Henry   
6              7         0       1               McCarthy, Mr. Timothy J   
13            14         0       3           Andersson, Mr. Anders Johan   
20            21         0       2                  Fynney, Mr. Joseph J   
21            22         1       2                 Beesley, Mr. Lawrence   
..           ...       ...     ...                                   ...   
867          868         0       1  Roebling, Mr. Washington Augustus II   
872          873         0       1              Carlsson, Mr. Frans Olof   
873          874         0       3           Vander Cruyssen, Mr. Victor   
881          882         0       3                    Markun, Mr. Johann   
890          891         0       3                   Dooley, Mr. Patrick   

      Sex   Age  SibSp  Parch    Ticket     Fare        Cabin Embarked  
4    male  35.0      0      0    373450   8.0500          NaN        S  
6    male  54.0      0      0     17463  51.8625          E46        S  
13   male  39.0      1      5    347082  31.2750          NaN        S  
20   male  35.0      0      0    239865  26.0000          NaN        S  
21   male  34.0      0      0    248698  13.0000          D56        S  
..    ...   ...    ...    ...       ...      ...          ...      ...  
867  male  31.0      0      0  PC 17590  50.4958          A24        S  
872  male  33.0      0      0       695   5.0000  B51 B53 B55        S  
873  male  47.0      0      0    345765   9.0000          NaN        S  
881  male  33.0      0      0    349257   7.8958          NaN        S  
890  male  32.0      0      0    370376   7.7500          NaN        Q  

[216 rows x 12 columns]

In [134]:
data.loc[((data["Age"]>=30)&(data["Sex"]=="male")), ["Name", "Age", "Sex"]]

Name   Age   Sex
4                Allen, Mr. William Henry  35.0  male
6                 McCarthy, Mr. Timothy J  54.0  male
13            Andersson, Mr. Anders Johan  39.0  male
20                   Fynney, Mr. Joseph J  35.0  male
21                  Beesley, Mr. Lawrence  34.0  male
..                                    ...   ...   ...
867  Roebling, Mr. Washington Augustus II  31.0  male
872              Carlsson, Mr. Frans Olof  33.0  male
873           Vander Cruyssen, Mr. Victor  47.0  male
881                    Markun, Mr. Johann  33.0  male
890                   Dooley, Mr. Patrick  32.0  male

[216 rows x 3 columns]

In [139]:
df = pd.DataFrame([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
df
df.index = ["Enero", "Febrero", "Marzo"]
df.columns = ["Ano 2020", "Ano 2021", "Ano 2022"]
df

Ano 2020  Ano 2021  Ano 2022
Enero           1         2         3
Febrero         4         5         6
Marzo           7         8         9

In [147]:
data.index = [i for i in range(1, len(data["Age"])+1, 1)]
data

PassengerId  Survived  Pclass  \
1              1         0       3   
2              2         1       1   
3              3         1       3   
4              4         1       1   
5              5         0       3   
..           ...       ...     ...   
887          887         0       2   
888          888         1       1   
889          889         0       3   
890          890         1       1   
891          891         0       3   

                                                  Name     Sex   Age  SibSp  \
1                              Braund, Mr. Owen Harris    male  22.0      1   
2    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
3                               Heikkinen, Miss. Laina  female  26.0      0   
4         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
5                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
887                              Montvila, Rev. Juozas    male  27.0      0   
888                       Graham, Miss. Margaret Edith  female  19.0      0   
889           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
890                              Behr, Mr. Karl Howell    male  26.0      0   
891                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
1        0         A/5 21171   7.2500   NaN        S  
2        0          PC 17599  71.2833   C85        C  
3        0  STON/O2. 3101282   7.9250   NaN        S  
4        0            113803  53.1000  C123        S  
5        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
887      0            211536  13.0000   NaN        S  
888      0            112053  30.0000   B42        S  
889      2        W./C. 6607  23.4500   NaN        S  
890      0            111369  30.0000  C148        C  
891      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]