In [1]:
import numpy as np
import pandas as pd
import matplotlib as plt
import random

- Ejercicio 1
    - Crear series a partir de listas y a partir de arrays
    - Crear dataframes a partir de listas anidadas, y de arrays anidados
    - Crear dataframes especificando etiquetas para las columnas
    - Cargar el dataframe del titanic, y visualizar la información basica del mismo

In [18]:
Buenas1 = [1, 2, 3]
print(Buenas1)
Buenas1 = pd.Series(Buenas1)
print(Buenas1)

Buenas2 = np.array([1, 2, 3, 4])
print(Buenas2)
Buenas2 = pd.Series(Buenas2)
print(Buenas2)

[1, 2, 3]
0    1
1    2
2    3
dtype: int64
[1 2 3 4]
0    1
1    2
2    3
3    4
dtype: int32


In [19]:
Buenas3 = [[1, 2], [3, 4]]
print(Buenas3)
Buenas3 = pd.DataFrame(Buenas3)
print(Buenas3)

Buenas4 = np.array([[1, 2], [3, 4]])
print(Buenas4)
Buenas4 = pd.DataFrame(Buenas4)
print(Buenas4)

[[1, 2], [3, 4]]
   0  1
0  1  2
1  3  4
[[1 2]
 [3 4]]
   0  1
0  1  2
1  3  4


In [27]:
Buenas5 = np.random.randint(1, 100, (4, 5))
print(Buenas5)

Buenas5 = pd.DataFrame(Buenas5, columns=["Columna 1", "Columna 2", "Columna 3", "Columna 4", "Columna 5"])
print(Buenas5)

[[16 38 35 92 96]
 [10 77 26 67  9]
 [47 94 19 21 32]
 [14 42 90 72 74]]
   Columna 1  Columna 2  Columna 3  Columna 4  Columna 5
0         16         38         35         92         96
1         10         77         26         67          9
2         47         94         19         21         32
3         14         42         90         72         74


In [36]:
DataTitanic = pd.read_csv("C:\\Users\\matia\\Desktop\\EducacionIT\\Archivos\\titanic.csv")
print(DataTitanic.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB
None


- Ejercicio 2
    - De titanic.csv , ya cargado como dataframe:
        - Seleccionar las columnas “Survived”, “Pclass”, “Age” y “Sex”.
        - Seleccionar las filas 200 a 400 de las columnas “Name” y “Age”.
        - Cambiar el nombre de la columna “PassengerId” por “ID”.
        - Seleccionar los datos de todas las mujeres de primera clase.
        - Seleccionar los datos de los varones menores de edad de segunda clase.

In [52]:
print(DataTitanic[["Survived", "Pclass", "Age", "Sex"]])
print(DataTitanic.loc[200:400, ["Name", "Age"]])

     Survived  Pclass   Age     Sex
0           0       3  22.0    male
1           1       1  38.0  female
2           1       3  26.0  female
3           1       1  35.0  female
4           0       3  35.0    male
..        ...     ...   ...     ...
886         0       2  27.0    male
887         1       1  19.0  female
888         0       3   NaN  female
889         1       1  26.0    male
890         0       3  32.0    male

[891 rows x 4 columns]
                                 Name   Age
200    Vande Walle, Mr. Nestor Cyriel  28.0
201               Sage, Mr. Frederick   NaN
202        Johanson, Mr. Jakob Alfred  34.0
203              Youseff, Mr. Gerious  45.5
204          Cohen, Mr. Gurshon "Gus"  18.0
..                                ...   ...
396               Olsson, Miss. Elina  31.0
397           McKane, Mr. Peter David  46.0
398                  Pain, Dr. Alfred  23.0
399  Trout, Mrs. William H (Jessie L)  28.0
400                Niskanen, Mr. Juha  39.0

[201 rows x 2 c

In [68]:
DataTitanic.rename(columns={"PassengerId":"ID"})

ID  Survived  Pclass                                               Name  \
0      1         0       3                            Braund, Mr. Owen Harris   
1      2         1       1  Cumings, Mrs. John Bradley (Florence Briggs Th...   
2      3         1       3                             Heikkinen, Miss. Laina   
3      4         1       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)   
4      5         0       3                           Allen, Mr. William Henry   
..   ...       ...     ...                                                ...   
886  887         0       2                              Montvila, Rev. Juozas   
887  888         1       1                       Graham, Miss. Margaret Edith   
888  889         0       3           Johnston, Miss. Catherine Helen "Carrie"   
889  890         1       1                              Behr, Mr. Karl Howell   
890  891         0       3                                Dooley, Mr. Patrick   

        Sex   Age  SibSp  Parch            Ticket     Fare Cabin Embarked  
0      male  22.0      1      0         A/5 21171   7.2500   NaN        S  
1    female  38.0      1      0          PC 17599  71.2833   C85        C  
2    female  26.0      0      0  STON/O2. 3101282   7.9250   NaN        S  
3    female  35.0      1      0            113803  53.1000  C123        S  
4      male  35.0      0      0            373450   8.0500   NaN        S  
..      ...   ...    ...    ...               ...      ...   ...      ...  
886    male  27.0      0      0            211536  13.0000   NaN        S  
887  female  19.0      0      0            112053  30.0000   B42        S  
888  female   NaN      1      2        W./C. 6607  23.4500   NaN        S  
889    male  26.0      0      0            111369  30.0000  C148        C  
890    male  32.0      0      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [87]:
#Seleccionar los datos de todas las mujeres de primera clase.

print(DataTitanic.loc[(DataTitanic["Sex"]=="female")&(DataTitanic["Pclass"]==1), ["Name", "Sex"]])
print(len(DataTitanic[(DataTitanic["Sex"]=="female")&(DataTitanic["Pclass"]==1)]))

                                                  Name     Sex
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female
11                            Bonnell, Miss. Elizabeth  female
31      Spencer, Mrs. William Augustus (Marie Eugenie)  female
52            Harper, Mrs. Henry Sleeper (Myna Haxtun)  female
..                                                 ...     ...
856         Wick, Mrs. George Dennick (Mary Hitchcock)  female
862  Swift, Mrs. Frederick Joel (Margaret Welles Ba...  female
871   Beckwith, Mrs. Richard Leonard (Sallie Monypeny)  female
879      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)  female
887                       Graham, Miss. Margaret Edith  female

[94 rows x 2 columns]
94


In [80]:
#Seleccionar los datos de los varones menores de edad de segunda clase.
print(DataTitanic[(DataTitanic["Sex"]=="male")&(DataTitanic["Age"]<18)&(DataTitanic["Pclass"]==2)])
print(len(DataTitanic[(DataTitanic["Sex"]=="male")&(DataTitanic["Age"]<18)&(DataTitanic["Pclass"]==2)]))

     PassengerId  Survived  Pclass                             Name   Sex  \
78            79         1       2    Caldwell, Master. Alden Gates  male   
183          184         1       2        Becker, Master. Richard F  male   
193          194         1       2       Navratil, Master. Michel M  male   
340          341         1       2   Navratil, Master. Edmond Roger  male   
407          408         1       2   Richards, Master. William Rowe  male   
549          550         1       2   Davies, Master. John Morgan Jr  male   
755          756         1       2        Hamalainen, Master. Viljo  male   
791          792         0       2              Gaskell, Mr. Alfred  male   
827          828         1       2            Mallet, Master. Andre  male   
831          832         1       2  Richards, Master. George Sibley  male   
841          842         0       2         Mudd, Mr. Thomas Charles  male   

       Age  SibSp  Parch           Ticket     Fare Cabin Embarked  
78    0

- Ejercicio 3
    - Del titanic.csv ya cargado como dataframe:
        - Encontrar el promedio de edad de hombres y de las  mujeres.
        - Encontrar la cantidad de sobrevivientes de hombres y las mujeres.


In [94]:
print("El promedio de edad de los varones en el Titanic, era de: ", DataTitanic[DataTitanic["Sex"]=="male"]["Age"].mean())
print("El promedio de edad de las mujeres en el Titanic era de: ", DataTitanic[DataTitanic["Sex"]=="female"]["Age"].mean())

El promedio de edad de los varones en el Titanic, era de:  30.72664459161148
El promedio de edad de las mujeres en el Titanic era de:  27.915708812260537


In [102]:
print("La cantidad de varones que sobrevivieron al Titanic fue de: ", len(DataTitanic.loc[(DataTitanic["Survived"]==1)&(DataTitanic["Sex"]=="male")]))
print("La cantidad de mujeres que sobrevivieron al Titanic fue de: ", len(DataTitanic.loc[(DataTitanic["Sex"]=="female")&(DataTitanic["Survived"]==1)]))

La cantidad de varones que sobrevivieron al Titanic fue de:  109
La cantidad de mujeres que sobrevivieron al Titanic fue de:  233


In [110]:
len(DataTitanic[DataTitanic["Survived"]==1])
print("En el Titanic viajaban ", len(DataTitanic), "personas.\nMurieron ", len(DataTitanic[DataTitanic["Survived"]==0]), "personas, y sobrevivieron ", len(DataTitanic[DataTitanic["Survived"]==1]), "personas.")

En el Titanic viajaban  891 personas.
Murieron  549 personas, y sobrevivieron  342 personas.
